podTemplate(containers: [
    containerTemplate(
        name: 'gradle',
        image: 'gradle:6.3-jdk14',
        command: 'sleep',
        args: '30d'
        ),
   ]) {
     node(POD_LABEL) {
         stage('Run pipeline against a gradle project') {
             git 'https://github.com/pyd6802/week6.git'
             container('gradle') {
                 stage('Build a gradle project') {
                     sh '''
                     cd Chapter08/sample1
                     chmod +x gradlew
                     ./gradlew test
                    '''
                    }
                 stage('Code coverage') {
                    sh 'echo CC Branch $BRANCH_NAME'
                    echo env.GIT_BRANCH
                    if(env.GIT_BRANCH == "master") {
                    step {
                        echo "I am the master branch, code coverage runs here"
                        try {
                            sh '''
                            pwd
                            cd Chapter08/sample1
                            ./gradlew jacocoTestCoverageVerification
                            ./gradlew jacocoTestReport
                            '''
                            } catch(e) {
                                echo "Code Coverage Failed - Not Master Branch"
                            }
                        publishHTML (target: [
                        reportDir: 'Chapter08/sample1/build/reports/jacoco/test/html',
                        reportFiles: 'index.html',
                        reportName: "JaCoCo Report"
                        ])
                        }
                    }
                    else {
                         echo "Code Coverage not applicable"
                         }
                    }
                 stage('Check style') {
                    sh 'echo CS Branch $BRANCH_NAME'
                    echo env.GIT_BRANCH
                    if(env.GIT_BRANCH != "playground") {
                    step {
                        echo "I am the master / feature branch, checkstyle runs here"
                        try { 
                            sh '''
                            pwd
                            cd Chapter08/sample1
                            ./gradlew checkstyleMain 
                        '''
                        } catch(e) {
                            echo "Checkstyle fails"
                        } 
                        publishHTML (target: [
                        reportDir: 'Chapter08/sample1/build/reports/checkstyle',
                        reportFiles: 'main.html',
                        reportName: "Checkstyle Report"
                        ])
                        }
                    }
                     else {
                         echo "CS Not applicable"
                         }
                    }
           }
       }
   }
 }